### ISSUE TITLE
.NET CoreのテストをDocker上で実行する

### ISSUE THREAD

**Issue by CreatioVitae** [CreatioVitae/kashilog#2]
# やりたいこと
.NET CoreのテストをDocker上で実行する

## 実際にやること
Docker上に.net Coreのアプリケーションの資産をコピーできる
Docker上でxUnitのテストが実行できる
テスト結果を表示できる
永続化層に関する簡単なテストを追加する

## 完了条件
上記がmasterにmergeされたら

**Comment by endongpz** [comment]
# .net coreアプリケーションのビルド
https://medium.com/faun/building-a-docker-image-with-gitlab-ci-and-net-core-8f59681a86c4

**Comment by endongpz** [comment]
# テストプロジェクトを作成し、簡素なテストをDocker上で動かす
## DockerFileに書くこと
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS testBuilder

# 依存関係の復元のためにcsprojファイルをdocker上にコピーしてくる
COPY "./tests/WebApi.Kashilog.Test/WebApi.Kashilog.Test.csproj" "./tests/WebApi.Kashilog.Test.csproj"

# 依存関係の復元
RUN dotnet restore "./tests/WebApi.Kashilog.Test.csproj"

# 依存関係を復元したソースファイルをコピーしてもってくる
COPY . .

# 作業フォルダの指定
WORKDIR /tests

# ビルド後にテストコマンド実行するように仕込み
ENTRYPOINT dotnet test
```
- FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS testBuilder
   WebApiのプロジェクトに合わせて.net core のSDKのバージョン3.1を使用する
- COPY "./tests/WebApi.Kashilog.Test/WebApi.Kashilog.Test.csproj" "./tests/WebApi.Kashilog.Test.csproj"
   依存関係をdotnet restoreコマンドで復元するために、依存関係を記述しているcsprojファイルをコピーして持ってくる
- RUN dotnet restore "./tests/WebApi.Kashilog.Test.csproj"
   依存関係の復元
- COPY . .
   復元したソースをDocker上に持ってくる
- WORKDIR /tests
   作業用ディレクトリにtestsを指定
- ENTRYPOINT dotnet test
   ビルド後に発火するコマンドを指定。この場合はテスト実行。

# トラブルシューティング
テスト実行時に以下のようなエラーに遭遇した場合
```
 Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/tests/WebApi.Kashilog.Test.csproj]
```
- testprojectのcsprojファイルに以下記述を追記
```
   <!-- DockerでTestを実行する際のエラー回避のために入れている（GenerateAssemblyInfoとGenerateTargetFrameworkAttribute)。-->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
```

**Comment by endongpz** [comment]
# テスト用DBのコンテナーを立ち上げた後に、testを実行するcontainerを起動する
https://matsuand.github.io/docs.docker.jp.onthefly/compose/startup-order/
```
version: '3.7'

services:
    kashilog-test-sql-server:
      build:
        context: ./Databases/MSSql/Tests
        dockerfile: DockerFile
      container_name: KashilogTestDB
      ports:
        - 15332:1433
    web-api-test:
      build:
        context: ./tests
        dockerfile: DockerFile
      container_name: KashilogTest
      depends_on:
        - "kashilog-test-sql-server"
      command: ["./wait-for-it.sh", "kashilog-test-sql-server:15332"]
```
wait-for-it.shと。
depends_onをつかって起動の順番を制御できる
※現在確認中

**Comment by endongpz** [comment]
## 独自のラッパースクリプトで、SQLServerの起動確認してからテストを実行する

```
```

## はまったこと
### exec format error
以下エラーが出た。
```
 standard_init_linux.go:211: exec user process caused "exec format error"
```
→Shellスクリプトの頭に以下記述が必要だった。
```
#!/bin/bash
```

**Comment by endongpz** [comment]
## mssql-cliのインストールでエラー
.net coreのimageをdebianにしてたら、apt-getでエラーが発生して失敗した。
```
E: Unable to locate package mssql-cli
```
→imageをUbuntuに変更したらいけた

**Comment by endongpz** [comment]
# wait-for-itを使ったやり方
Dockerのドキュメントでwait-for-itを使ったやり方がかいてある。
こちらを試してみる。
```
version: '3.7'

services:
    kashilog-test-sql-server:
      build:
        context: ./Databases/MSSql/Tests
        dockerfile: Dockerfile
      container_name: KashilogTestDB
      ports:
        - 15332:1433
    web-api-test:
      build:
        context: ./tests
        dockerfile: Dockerfile
      container_name: KashilogTest
      volumes:
        - ./tests/wait-for-it.sh
      depends_on:
        - "kashilog-test-sql-server"
      command: ["./wait-for-it.sh", "kashilog-test-sql-server:15332",  "-t", "60", "--", "dotnet",  "test"]
```
-   "-t", "60"
　→こいつがあることで60秒起動までまつみたい。
確実な方法で考えると、カスタムスクリプト。
wait-for-itは場当たり的な対応に感じる・・・
