### ISSUE TITLE
vsでのデバッグをdocker-composeでdb込でのコンテナ駆動にする

### ISSUE THREAD

**Issue by CreatioVitae** [CreatioVitae/kashilog#3]
https://docs.microsoft.com/ja-jp/visualstudio/containers/tutorial-multicontainer?view=vs-2019

**Comment by endongpz** [comment]
# VisualStudioで、docker-composeで起動できるようにする
https://docs.microsoft.com/ja-jp/visualstudio/containers/tutorial-multicontainer?view=vs-2019
## docker-composeにプロジェクトを追加
- プロジェクトの上で右クリック
- 追加＞コンテナーオーケストレーターのサポート
- オーケストレータ:Docker ComposeでOKを選択
- ターゲットOS：LinuxでOKを選択
- (新しいDockerfileを作成しますか？とでてきたらはい(Y)を選択)
- (上書きしますか？とでてきたらはい(Y)を選択)
※今回の場合は、WebApiとManagementで2回実行する
すると以下のようなyamlファイルが作成される
```
version: '3.4'

services:
  webapi.kashilog:
    image: ${DOCKER_REGISTRY-}webapikashilog
    build:
      context: .
      dockerfile: WebApi.Kashilog/Dockerfile

  management.kashilog:
    image: ${DOCKER_REGISTRY-}managementkashilog
    build:
      context: .
      dockerfile: Management.Kashilog/Dockerfile
```
## SQLServerのコンテナーを追加
上記yamlを以下のように編集する
```
version: '3.4'

services:
  webapi.kashilog:
    image: ${DOCKER_REGISTRY-}webapikashilog
    build:
      context: .
      dockerfile: WebApi.Kashilog/Dockerfile

  management.kashilog:
    image: ${DOCKER_REGISTRY-}managementkashilog
    build:
      context: .
      dockerfile: Management.Kashilog/Dockerfile

  kashilog-sql-server:
    build:
      context: ../Databases/MSSql/DevLocal
      dockerfile: Dockerfile
    container_name: KashilogDevLocalDB
    ports:
      - 15331:1433
```
※インデントでフォーマットが有効かどうかが判別される（kashilog-sql-server:の前のスペースが多かったりすくなかったりするとエラーとなってdocker-composeで起動できなくなるので注意。基本的にスペース2個で1つのインデントになります。

**Comment by endongpz** [comment]
# はまっていること
https://localhost:13330/product
で何も表示されない

**Comment by endongpz** [comment]
# 課題
外部への露出ポートと、内部ポートを合致させれば（EXPOSEの設定含め）、サイトは見ることができたが、
外部への露出ポートと内部ポートをずらした際に、表示ができなくなる。

ここら辺の設定がわかっていない

**Comment by endongpz** [comment]
# VisualStudioでのdocker-composeサポート
## プロジェクト名
デフォルトではdocker-composeというプロジェクト名になるが、docker-compose-webapiなど変更をしても問題なく起動できる
→slnファイルの中の記述がかわる
## docker-compose.ymlのファイル名
変更するとエラーで落ちる。
```
"ResolveTargetOS" タスクが予期せずに失敗しました。
Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: ファイル 'C:\Users\XXXX\source\repos\kashilog\support-docker-compose\kashilog\src\docker-compose.yml' が見つかりませんでした。
```
→Microsoft.VisualStudio.Containers.Toolsで検索してみたがソース見つけられず。名前的にいじれなそうな場所。
また、docker-compose.ymlのファイル名を変更してもdcproj内のdocker-compose.ymlに対しての参照名が書き換わらないため、VS立ち上げなおすとファイルが見つからない旨を示すエラーが表示される。

**Comment by endongpz** [comment]
# docker-compose実行時にSQLServerのコンテナーが立ち上がっていなかったら立ち上げるようにする
## 方針
・SQLServerのコンテナーが立ち上がっているか確認
・立ち上がっていなかったらdockerコマンドつかってコンテナー立ち上げる
（imageがあるか？コンテナーが存在しているか？コンテナーが存在しているけどたちあがっていないか？というパターンが考えられるので、すべてチェックしてから状況に応じて発行するコマンドを変更する）
・上記ような処理をするshellスクリプトを用意して、docker-composeのentrypointで実行する

## はまっていること
Dockerfile内のCOPYについて、
COPY a b
としたときに、
bは、Docker上なのでWORKDIRを指定することでいろいろと変更ができるが、
aは、docker buildのばあい、コマンドを実行したディレクトリに依存してしまっている。
※例えば以下ディレクトリ構造があったときに
📂Databases
 ∟📂Mssql
 　∟Dockerfile
　 ∟TestDb.bacpac

Dockerfileで、以下のような記述をしていると
```
COPY TestDb.bacpac /tmp/testdb.bacpac
```

Mssqlまで遷移して以下コマンドを実行すると問題なくビルドができる
```
docker build -f Dockerfile -t testdb .
```
※-f Dockerfileは省略可能だが、対比のためにわざと書いています
しかし、Databasesまで遷移して以下コマンドを実行するとエラーが発生する
```
docker build -f ./Mssql/Dockerfile -t testdb .
```
この場合は、以下のようなエラーメッセージが表示される
```
COPY failed: file not found in build context or excluded by .dockerignore: stat TestDb.bacpac: file does not exist
```
ここで、上記パターンでせいこうするDockerfileの記述は以下のようになる。
```
COPY ./Mssql/TestDb.bacpac /tmp/testdb.bacpac
```
思いっきりコマンドを実行するディレクトリがCOPYコマンドのときに参照されてしまっている。

**Comment by endongpz** [comment]
# docker-compose up と、docker-compose build → docker-compose runの違いについて
以下のようなyamlファイルがある
```
version: '3.7'

services: 
    kashiloglocaldb:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: KashilogDevLocalDB
      ports:
        - 15331:1433
```
これを使ってcontainerを立ち上げる時に、
docker-compose upする方法と、
docker-compose buildしたあとに、docker-compose runする方法がある。
## docker-compose up
以下コマンドを実行する
```
 docker-compose -f ./Databases/MSSql/DevLocal/docker-compose-devlocal.yaml up -d
```
以下のようなコンテナーが作成される(docker psした結果)
|CONTAINER ID |IMAGE|COMMAND|CREATED|STATUS|PORTS|NAMES|h
|c261fc7da58e|devlocal_kashiloglocaldb|"/opt/mssql/bin/nonr…" |30 seconds ago|Up 28 seconds|0.0.0.0:15331->1433/tcp |KashilogDevLocalDB|
このコマンドをもう一度実行しても以下のようなメッセージが出てコンテナは新たに立ち上がることはない
```
KashilogDevLocalDB is up-to-date
```
## docker-compose build実行後、docker-compose run実行
まず最初にbuildする
```
docker-compose -f ./Databases/MSSql/DevLocal/docker-compose-devlocal.yaml build
```
imageが作成される
```
～中略～
Successfully built 1f91cd10f18d
Successfully tagged devlocal_kashiloglocaldb:latest
```
